-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 14:21:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `food` ;

-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food` DEFAULT CHARACTER SET utf8 ;
USE `food` ;

-- -----------------------------------------------------
-- Table `food`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`country` ;

CREATE TABLE IF NOT EXISTS `food`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `language` VARCHAR(45) NULL,
  `language_short` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`.`meal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`meal` ;

CREATE TABLE IF NOT EXISTS `food`.`meal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`.`country_meal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`country_meal` ;

CREATE TABLE IF NOT EXISTS `food`.`country_meal` (
  `id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `meal_id` INT NOT NULL,
  PRIMARY KEY (`id`, `country_id`, `meal_id`),
  INDEX `fk_country_meal_country1_idx` (`country_id` ASC) ,
  INDEX `fk_country_meal_meal1_idx` (`meal_id` ASC) ,
  CONSTRAINT `fk_country_meal_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `food`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_meal_meal1`
    FOREIGN KEY (`meal_id`)
    REFERENCES `food`.`meal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`.`nutrient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`nutrient` ;

CREATE TABLE IF NOT EXISTS `food`.`nutrient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`.`meal_nutrient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`meal_nutrient` ;

CREATE TABLE IF NOT EXISTS `food`.`meal_nutrient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meal_id` INT NOT NULL,
  `nutrient_id` INT NOT NULL,
  `amount` FLOAT NULL,
  `unit` VARCHAR(10) NULL,
  PRIMARY KEY (`id`, `meal_id`, `nutrient_id`),
  INDEX `fk_meal_nutrient_meal1_idx` (`meal_id` ASC) ,
  INDEX `fk_meal_nutrient_nutrient1_idx` (`nutrient_id` ASC) ,
  CONSTRAINT `fk_meal_nutrient_meal1`
    FOREIGN KEY (`meal_id`)
    REFERENCES `food`.`meal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meal_nutrient_nutrient1`
    FOREIGN KEY (`nutrient_id`)
    REFERENCES `food`.`nutrient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
